### ISSUE TITLE
Harvester Upgrade Causes Crash for Melons/Pumpkins

### ISSUE THREAD

**Issue by Schaawne** [Mowmaster/Pedestals#206]
Modpack: FTB Skies 1.0.6

Steps:
1. Plant melons/pumpkins
2. Set work area to locations where melons/pumpkins will spawn (not the seeded locations)
3. Apply work area to pedestal
4. Apply harvester to pedestal (NOTE: Mine was 40/40 speed, range upgrade 8, first crash was with gentle harvest second without)
5. Impending crash

Console Log:
`
[04May2023 23:54:49.839] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:870) ~[server-1.19.2-20220805.130853-srg.jar%23683!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23683!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23683!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23683!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23683!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.properties.IntegerProperty.m_6908_()" because "propInt" is null
	at com.mowmaster.pedestals.Items.Upgrades.Pedestal.ItemUpgradeHarvester.harvesterAction(ItemUpgradeHarvester.java:684) ~[pedestals-0.2.47.jar%23593!/:0.2.47]
	at com.mowmaster.pedestals.Items.Upgrades.Pedestal.ItemUpgradeHarvester.upgradeAction(ItemUpgradeHarvester.java:267) ~[pedestals-0.2.47.jar%23593!/:0.2.47]
	at com.mowmaster.pedestals.Items.Upgrades.Pedestal.ItemUpgradeBase.updateAction(ItemUpgradeBase.java:88) ~[pedestals-0.2.47.jar%23593!/:0.2.47]
	at com.mowmaster.pedestals.Blocks.Pedestal.BasePedestalBlockEntity.tick(BasePedestalBlockEntity.java:3635) ~[pedestals-0.2.47.jar%23593!/:0.2.47]
	at com.mowmaster.pedestals.Blocks.Pedestal.BasePedestalBlock.lambda$getTicker$0(BasePedestalBlock.java:1140) ~[pedestals-0.2.47.jar%23593!/:0.2.47]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[server-1.19.2-20220805.130853-srg.jar%23683!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[server-1.19.2-20220805.130853-srg.jar%23683!/:?]
	at net.minecraft.world.level.Level.m_46463_(MixinLevel.java:446) ~[server-1.19.2-20220805.130853-srg.jar%23683!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[server-1.19.2-20220805.130853-srg.jar%23683!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23683!/:?]
	... 5 more
`

**Comment by Mowmaster** [comment]
https://github.com/Mowmaster/Pedestals/commit/fe0d8410657af478a9c3510d5760352a8dd7188b
