### ISSUE TITLE
[issue] pedestals xp farmer causes crash

### ISSUE THREAD

**Issue by AlexanderStroer** [Mowmaster/Pedestals#256]
Placing a pedestal on top of a Sculk Catalyst and feeding liquid experience through a Pipez fluid pipe from an Ender Tank causes the pedestal to have packaged fluid once the pedestal is broken, once broken this causes a hanging entity crash for the server. This was replicated numerous times

---- Minecraft Crash Report ----
// There are four lights!

Time: 2023-12-26 23:05:44
Description: Watching Server

java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
	at com.mowmaster.pedestals.Items.MechanicalOnlyStorage.BaseFluidBulkStorageItem.removeFluid(BaseFluidBulkStorageItem.java:248) ~[pedestals-0.4.56.jar%23576!/:0.4.56] {re:classloading}
	at com.mowmaster.pedestals.Items.MechanicalOnlyStorage.BaseFluidBulkStorageItem.m_6883_(BaseFluidBulkStorageItem.java:211) ~[pedestals-0.4.56.jar%23576!/:0.4.56] {re:classloading}

**Comment by AlexanderStroer** [comment]
This was on the FTB DireWolf 1.20 1.10.0 modpack.

**Comment by Mowmaster** [comment]
did some 1.19 testing, this might only effect 1.20, something to do with the remove fluid function probably on the while loop as it spawns fluid in world
