### ISSUE TITLE
Placing bucket on pedestal with Fluid tank upgrade crashes server.

### ISSUE THREAD

**Issue by megastary** [Mowmaster/Pedestals#55]
Version: 0.8r_hotfix_4
Forge version: 36.0.46
Modpack: ATM6 1.5.4

So I was trying to figure out fluid upgrades and have made following setup.
Pedestal with import fluid upgrade on top of water tank linked to Pedestal with fluid tank upgrade linked to pedestal with fluid export upgrade on top of empty tank.
Nothing was happening, so I placed empty bucket on pedestal with fluid tank upgrade and server crashed.

Log:
```
minecraft    | [16:00:10] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID ba2f7905-2fea-4e06-b6ec-786d85dc8b7d
minecraft    | [16:00:10] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
minecraft    | net.minecraft.crash.ReportedException: Ticking block entity
minecraft    |  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
minecraft    |  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
minecraft    |  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
minecraft    |  at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
minecraft    |  at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
minecraft    |  at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}
minecraft    | Caused by: java.util.NoSuchElementException: No value present
minecraft    |  at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_212] {}
minecraft    |  at com.mowmaster.pedestals.item.pedestalUpgrades.ItemUpgradeFluidImport.getFluidInItem(ItemUpgradeFluidImport.java:112) ~[pedestals:0.8r_hotfix_4] {re:classloading,pl:runtimedistcleaner:A}
minecraft    |  at com.mowmaster.pedestals.item.pedestalUpgrades.ItemUpgradeFluidImport.canAcceptCount(ItemUpgradeFluidImport.java:60) ~[pedestals:0.8r_hotfix_4] {re:classloading,pl:runtimedistcleaner:A}
minecraft    |  at com.mowmaster.pedestals.tiles.PedestalTileEntity.canAcceptItems(PedestalTileEntity.java:1291) ~[pedestals:0.8r_hotfix_4] {re:classloading}
minecraft    |  at com.mowmaster.pedestals.tiles.PedestalTileEntity.canSendToPedestal(PedestalTileEntity.java:1405) ~[pedestals:0.8r_hotfix_4] {re:classloading}
minecraft    |  at com.mowmaster.pedestals.tiles.PedestalTileEntity.func_73660_a(PedestalTileEntity.java:1578) ~[pedestals:0.8r_hotfix_4] {re:classloading}
minecraft    |  at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:runtimedistcleaner:A}
minecraft    |  at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
minecraft    |  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
minecraft    |  ... 5 more
```

Next server start crashes with following logs:
```
[16:11:46] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 672401fc-e0ad-46c7-a1d8-1be9abee1c60
[16:11:46] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_212] {}
        at com.mowmaster.pedestals.item.pedestalUpgrades.ItemUpgradeFluidImport.getFluidInItem(ItemUpgradeFluidImport.java:112) ~[pedestals:0.8r_hotfix_4] {re:classloading,pl:runtimedistcleaner:A}
        at com.mowmaster.pedestals.item.pedestalUpgrades.ItemUpgradeFluidImport.canAcceptCount(ItemUpgradeFluidImport.java:60) ~[pedestals:0.8r_hotfix_4] {re:classloading,pl:runtimedistcleaner:A}
        at com.mowmaster.pedestals.tiles.PedestalTileEntity.canAcceptItems(PedestalTileEntity.java:1291) ~[pedestals:0.8r_hotfix_4] {re:classloading}
        at com.mowmaster.pedestals.tiles.PedestalTileEntity.canSendToPedestal(PedestalTileEntity.java:1405) ~[pedestals:0.8r_hotfix_4] {re:classloading}
        at com.mowmaster.pedestals.tiles.PedestalTileEntity.func_73660_a(PedestalTileEntity.java:1578) ~[pedestals:0.8r_hotfix_4] {re:classloading}
        at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        ... 5 more
[16:11:50] [Server thread/ERROR] [minecraft/ChunkSerializer]: An Entity type entity.minecolonies.citizen has thrown an exception trying to write state. It will not persist. Report this to the mod author
net.minecraft.crash.ReportedException: Saving entity NBT
        at net.minecraft.entity.Entity.func_189511_e(Entity.java:1433) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,pl:mixin:APP:randompatches.mixins.json:EntityMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.EntityAccess,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_184198_c(Entity.java:1347) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,pl:mixin:APP:randompatches.mixins.json:EntityMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.EntityAccess,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.Entity.func_70039_c(Entity.java:1355) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,pl:mixin:APP:randompatches.mixins.json:EntityMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.EntityAccess,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.chunk.storage.ChunkSerializer.func_222645_a(ChunkSerializer.java:303) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:chocolate.mixins.json:world.chunk.storage.ChunkSerializerMixin,pl:mixin:A}
        at net.minecraft.world.server.ChunkManager.func_219229_a(ChunkManager.java:682) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_212] {}
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212] {}
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_212] {}
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_212] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212] {}
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_212] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_212] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212] {}
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_212] {}
        at net.minecraft.world.server.ChunkManager.func_219177_a(ChunkManager.java:337) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerChunkProvider.func_217210_a(ServerChunkProvider.java:307) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerChunkProvider.close(ServerChunkProvider.java:311) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.close(World.java:706) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:574) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:514) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:679) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}
Caused by: java.lang.NullPointerException
        at com.minecolonies.coremod.util.AdvancementUtils.TriggerAdvancementPlayersForColony(AdvancementUtils.java:21) ~[minecolonies:0.13.692-ALPHA] {re:classloading}
        at com.minecolonies.coremod.entity.citizen.citizenhandlers.CitizenJobHandler.onJobChanged(CitizenJobHandler.java:130) ~[minecolonies:0.13.692-ALPHA] {re:classloading}
        at com.minecolonies.coremod.colony.CitizenData.initEntityValues(CitizenData.java:415) ~[minecolonies:0.13.692-ALPHA] {re:classloading}
        at com.minecolonies.coremod.entity.citizen.EntityCitizen.setCivilianData(EntityCitizen.java:721) ~[minecolonies:0.13.692-ALPHA] {re:classloading}
        at com.minecolonies.coremod.colony.CitizenData.setEntity(CitizenData.java:284) ~[minecolonies:0.13.692-ALPHA] {re:classloading}
        at com.minecolonies.coremod.colony.managers.CitizenManager.registerCivilian(CitizenManager.java:120) ~[minecolonies:0.13.692-ALPHA] {re:classloading}
        at com.minecolonies.coremod.entity.citizen.CitizenColonyHandler.registerWithColony(CitizenColonyHandler.java:104) ~[minecolonies:0.13.692-ALPHA] {re:classloading}
        at com.minecolonies.coremod.entity.citizen.CitizenColonyHandler.getColony(CitizenColonyHandler.java:160) ~[minecolonies:0.13.692-ALPHA] {re:classloading}
        at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_213281_b(EntityCitizen.java:416) ~[minecolonies:0.13.692-ALPHA] {re:classloading}
        at net.minecraft.entity.Entity.func_189511_e(Entity.java:1412) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,pl:mixin:APP:randompatches.mixins.json:EntityMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.EntityAccess,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        ... 23 more
[16:12:46] [INFO] Server has been stopped, it has started 1 times in 60min
```

**Comment by Mowmaster** [comment]
In the future, please use pastebin or some site to host the insanely long crash reports.

This has been fixed already, https://github.com/Mowmaster/Pedestals/commit/22445bb2679fe75de368e80f5fc3837134329f73

Currently, until the mod updates to 0.8t+ your work around are to downgrade your server to forge version 1.16.5 -##.##.39 or lower (forge v40 broke some fluid handling which is why this crash occurs)
OR, what I personally recommend, in the server world configuration folder, there is a config for forge,  in there is a way to "remove erroring tile entities" doing this should prevent server crashloops if anything does break, in any mod.
